/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContentType = IDL.Variant({
  'link' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'contentType' : ContentType,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, ContentType, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContentType = IDL.Variant({
    'link' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'contentType' : ContentType,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, ContentType, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };