/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContentType = { 'link' : null } |
  { 'text' : null } |
  { 'image' : null };
export interface Post {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'contentType' : ContentType,
  'description' : string,
  'imageUrl' : [] | [string],
  'timestamp' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'createPost' : ActorMethod<
    [string, string, ContentType, string, [] | [string]],
    bigint
  >,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getPost' : ActorMethod<[bigint], Post>,
  'searchPosts' : ActorMethod<[string], Array<Post>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];